import te200 from "./te200.png"
import tp200 from "./tp200.png"
import tc200 from "./tc200.png"
import nd250 from "./nd250.png"
import tba100 from "./tba100.png"
import bu250 from "./bu250.png"
import st100 from "./st100.png"
import sus250 from "./sus250.png"

interface Product {
    id: number;
    name: string;
    concentration: number;
    picture: string;
    inStock: boolean;
    quantity: number;
    value: number;
    discount: number;
  }
  
  // Array de objetos
  const products: Product[] = [
    {   id: 1,
        name: "Enantato de Testosterona",
        concentration: 200,
        picture: te200,
        inStock: true,
        quantity: 1,
        value: 180.00,
        discount: 0,
    },
    {   id: 2,
        name: "3x Enantato de Testosterona",
        concentration: 200,
        picture: te200,
        inStock: true,
        quantity: 3,
        value: 500.00,
        discount: 40.00,
    },
    {   id: 3,
        name: "Propionato de Testosterona",
        concentration: 200,
        picture: tp200,
        inStock: true,
        quantity: 1,
        value: 180.00,
        discount: 0,
    },
    {   id: 4,
        name: "3x Propionato de Testosterona",
        concentration: 200,
        picture: tp200,
        inStock: true,
        quantity: 3,
        value: 500.00,
        discount: 40.00,
    },
    {   id: 5,
        name: "Cipionato de Testosterona",
        concentration: 200,
        picture: tc200,
        inStock: false,
        quantity: 1,
        value: 180.00,
        discount: 0,
    },
    {   id: 6,
        name: "3x Cipionato de Testosterona",
        concentration: 200,
        picture: tc200,
        inStock: false,
        quantity: 3,
        value: 500.00,
        discount: 40.00,
    },
    {   id: 7,
        name: "Decanoato de Nandrolona",
        concentration: 250,
        picture: nd250,
        inStock: false,
        quantity: 1,
        value: 200.00,
        discount: 0,
    },
    {   id: 8,
        name: "3x Decanoato de Nandrolona",
        concentration: 250,
        picture: nd250,
        inStock: false,
        quantity: 3,
        value: 550.00,
        discount: 50.00,
    },
    {   id: 9,
        name: "Acetato de Trembolona",
        concentration: 100,
        picture: tba100,
        inStock: false,
        quantity: 1,
        value: 200.00,
        discount: 0,
    },
    {   id: 10,
        name: "3x Acetato de Trembolona",
        concentration: 100,
        picture: tba100,
        inStock: false,
        quantity: 3,
        value: 550.00,
        discount: 50.00,
    },
    {   id: 11,
        name: "Boldenona",
        concentration: 250,
        picture: bu250,
        inStock: false,
        quantity: 1,
        value: 200.00,
        discount: 0,
    },
    {   id: 12,
        name: "3x Boldenona",
        concentration: 250,
        picture: bu250,
        inStock: false,
        quantity: 3,
        value: 550.00,
        discount: 50.00,
    },
    {   id: 13,
        name: "Stanozolol",
        concentration: 100,
        picture: st100,
        inStock: false,
        quantity: 1,
        value: 200.00,
        discount: 0,
    },
    {   id: 14,
        name: "3x Stanozolol",
        concentration: 100,
        picture: st100,
        inStock: false,
        quantity: 3,
        value: 550.00,
        discount: 50.00,
    },
    {   id: 15,
        name: "Durateston",
        concentration: 250,
        picture: sus250,
        inStock: false,
        quantity: 1,
        value: 200.00,
        discount: 0,
    },
    {   id: 16,
        name: "3x Durateston",
        concentration: 250,
        picture: sus250,
        inStock: false,
        quantity: 3,
        value: 550.00,
        discount: 50.00,
    },

  ];
  
  // Exportando a constante
  export default products;